### ISSUE TITLE
heavy lifting with computedfields

### ISSUE THREAD

**Issue by jerch** [opengisch/sylvis#17]
@olivierdalang Saw that you plan to do some heavy lifting in the project with computedfields. I really wonder how the updates will perform for you, esp. `Sector.computed_geom` looks nasty to me (without knowing how expensive your polygon tasks are there, yet alone the fact that it depends on itself from children + does two more `.all()` evaluations sounds like some real db stress).

In computedfields there are still some perf optimizations pending, like DFS vs. BFS or the missing partial transitive reduction, when operating on cycling structures (like trees). On trees there are further update shortcuts possible (like omitting full ascending updates for every deep node), which are currently not respected by the update resolver.

If you find bottlenecks here or have some profiling data - feel free to ping me back.

**Comment by olivierdalang** [comment]
Hi @jerch ! Thanks for your inputs here :-)

At this stage, it's a prototype, so we're not too concerned about performance (more about code simplicity), but we'll keep an eye on it if/when we scale up. We will let you know if we come across issues or ideas for further optimisation !
